#! /bin/sh

set -e

cd "$(dirname "$0")/.."

echo "=> Installing ezshare-raspberry and ezshare-usbdcim script...\n"
sudo cp ezshare.py /usr/local/bin/
sudo cp usbdcim.py /usr/local/bin/
sudo chmod +x /usr/local/bin/ezshare.py
sudo chmod +x /usr/local/bin/usbdcim.py

echo "=> Starting ezshare-raspberry and ezshare-usbdcim service...\n"
sudo cp ezshare-raspberry.service /etc/systemd/system/
sudo cp usbdcim-raspberry.service /etc/systemd/system/
sudo chmod 644 /etc/systemd/system/ezshare-raspberry.service
sudo chmod 644 /etc/systemd/system/usbdcim-raspberry.service

sudo systemctl start ezshare-raspberry
sudo systemctl start usbdcim-raspberry
sudo systemctl enable ezshare-raspberry
sudo systemctl enable usbdcim-raspberry

echo "Success: ezshare-raspberry and usbdcim-raspberry scripts installed!\n"
